#!/usr/bin/env python3
"""
Export Pareto-optimal configurations from JSON files to CSV format.

This script reads Pareto front JSON files generated by exhaustive_search.py
and exports all configurations to CSV files compatible with the sweep_configs
system. Uses the standard naming convention from sweep_configs/gen_sweep_configs.py.

Usage:
    python3 export_pareto_configs.py --input-dir pareto_comparison_des/ --side des
    python3 export_pareto_configs.py --input-dir pareto_comparison_ser/ --side ser

Output:
    - {side}_validation_configs.csv              - All unique Pareto configs
    - {side}_validation_candidates.csv           - Recommended validation points
    - {side}_validation_candidates_all_models.csv - Validation candidates across ALL models
    - {side}_validation_configs_{model}.csv      - Per-model exports
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd

# Acronym labels from sweep_configs/gen_sweep_configs.py
DES_ACRONYM_LABEL_BY_KEY = {
    "des_top_descriptor_reqs": "DTD",
    "des_top_memloader_reqs": "DTM",
    "des_cr_rocc_commands": "DC",
    "des_dth_l1_reqs": "DDL",
    "des_dth_fd_reqs": "DDFQ",
    "des_dth_fd_resps": "DDFP",
    "des_fw_l1_reqs": "DFL",
    "des_ml_buf_info_q": "DMB",
    "des_ml_load_info_q": "DML",
}

SER_ACRONYM_LABEL_BY_KEY = {
    "ser_field_handlers": "SF",
    "ser_cr_rocc_commands": "SC",
    "ser_dth_hasbits_reqs": "SDH",
    "ser_dth_descriptor_reqs": "SDD",
    "ser_dth_reg_resps": "SDQ",
    "ser_dth_reqs_meta": "SDM",
    "ser_dth_fh_outputs": "SDF",
    "ser_mw_write_input": "SMI",
    "ser_mw_write_inject": "SMJ",
    "ser_mw_write_ptrs": "SMP",
}

# Parameter key ordering (matches sweep_configs)
DES_KEYS = (
    "des_top_descriptor_reqs",
    "des_top_memloader_reqs",
    "des_cr_rocc_commands",
    "des_dth_l1_reqs",
    "des_dth_fd_reqs",
    "des_dth_fd_resps",
    "des_fw_l1_reqs",
    "des_ml_buf_info_q",
    "des_ml_load_info_q",
)

SER_KEYS = (
    "ser_field_handlers",
    "ser_cr_rocc_commands",
    "ser_dth_hasbits_reqs",
    "ser_dth_descriptor_reqs",
    "ser_dth_reg_resps",
    "ser_dth_reqs_meta",
    "ser_dth_fh_outputs",
    "ser_mw_write_input",
    "ser_mw_write_inject",
    "ser_mw_write_ptrs",
)


def generate_config_name(config: dict[str, int], side: str, sweep_type: str = "Synth") -> str:
    """Generate config name using sweep_configs naming convention.

    Format: ProtoAccel{Side}{SweepType}{ACRONYM+VALUE}*Config
    Example: ProtoAccelDesSynthDTD4DTM64DC4DDL4Config

    Uses "Synth" to match synthesis sweep pattern for S3 cache hit tracking.
    """
    if side == "des":
        acronyms = DES_ACRONYM_LABEL_BY_KEY
        keys = DES_KEYS
        side_name = "Des"
    else:
        acronyms = SER_ACRONYM_LABEL_BY_KEY
        keys = SER_KEYS
        side_name = "Ser"

    # Build acronym+value encoding
    acronym_parts = []
    for key in keys:
        if key in config:
            acronym = acronyms[key]
            value = int(config[key])
            acronym_parts.append(f"{acronym}{value}")

    config_name = f"ProtoAccel{side_name}{sweep_type}{''.join(acronym_parts)}Config"
    return config_name


def load_pareto_data(path: Path) -> dict[str, Any]:
    """Load Pareto front data from JSON file."""
    with open(path, "r") as f:
        return json.load(f)


def find_pareto_files(input_dir: Path, side: str) -> dict[str, Path]:
    """Find all Pareto JSON files for a given side."""
    pattern = f"pareto_{side}_*.json"
    pareto_files = {}

    for path in input_dir.glob(pattern):
        # Extract model type from filename
        # Format: pareto_{side}_{model}.json
        stem = path.stem
        parts = stem.split("_")
        if len(parts) >= 3:
            model_type = "_".join(parts[2:])  # Handle multi-word model names
            pareto_files[model_type] = path

    return pareto_files


def export_configs_to_json(
    pareto_files: dict[str, Path],
    side: str,
    output_dir: Path,
) -> None:
    """Export all Pareto configs to a combined JSON file."""
    print(f"\n{'='*80}")
    print(f"Exporting validation configs for {side}")
    print(f"{'='*80}")

    # Create output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    all_configs = []
    config_signatures = set()  # For deduplication by params only

    param_keys = DES_KEYS if side == "des" else SER_KEYS

    for model_type, path in pareto_files.items():
        print(f"\nProcessing {model_type}...")
        data = load_pareto_data(path)

        for point in data["pareto_front"]:
            config = point["config"]

            # Create config signature for deduplication (params only)
            config_sig = tuple(config.get(k, 0) for k in param_keys)

            # Generate standard config name
            config_name = generate_config_name(config, side)

            # Build row
            row = {
                "config_name": config_name,
                "side": side,
                "sample_group": "pareto_validation",  # Matches synth CSV format
                "model_type": model_type,
                "validation_candidate": point["validation_candidate"],
                "predicted_throughput_gbits_per_sec": point["predicted_throughput_gbits_per_sec"],
            }

            # Add cost metrics
            if "predicted_logic_cells" in point:
                row["predicted_logic_cells"] = point["predicted_logic_cells"]
                row["predicted_ram_bits"] = point["predicted_ram_bits"]
                row["predicted_cost_scalar"] = point.get("predicted_cost_scalar_kappa", 0)
            else:
                row["predicted_cost"] = point["predicted_cost"]

            # Add all config parameters in canonical order
            for key in param_keys:
                row[key] = config.get(key, 0)

            all_configs.append(row)
            config_signatures.add(config_sig)

        print(f"  Loaded {len([p for p in data['pareto_front']])} configs from {model_type}")

    if not all_configs:
        print("\nWARNING: No configs to export")
        return

    print(f"\nTotal configs loaded: {len(all_configs)}")
    print(f"Unique parameter combinations: {len(config_signatures)}")

    # Sort by throughput descending
    all_configs_sorted = sorted(all_configs, key=lambda x: x["predicted_throughput_gbits_per_sec"], reverse=True)

    # Separate validation candidates
    validation_candidates = [c for c in all_configs_sorted if c["validation_candidate"]]

    # Create combined JSON structure
    combined_json = {
        "side": side,
        "total_configs": len(all_configs_sorted),
        "unique_parameter_combinations": len(config_signatures),
        "models": sorted(list(pareto_files.keys())),
        "num_validation_candidates": len(validation_candidates),
        "configs": all_configs_sorted,
    }

    # Export combined JSON
    output_path = output_dir / f"{side}_pareto_validation_configs.json"
    with open(output_path, "w") as f:
        json.dump(combined_json, f, indent=2)
    print(f"\n✓ Exported {len(all_configs_sorted)} total configs to: {output_path.name}")
    print(f"  - Validation candidates: {len(validation_candidates)}")
    print(f"  - Unique parameter combinations: {len(config_signatures)}")

    # Generate summary statistics
    print(f"\n{'='*80}")
    print("Summary Statistics")
    print(f"{'='*80}")

    model_stats = {}
    for config in all_configs_sorted:
        model = config["model_type"]
        if model not in model_stats:
            model_stats[model] = {
                "total": 0,
                "validation": 0,
                "throughputs": []
            }
        model_stats[model]["total"] += 1
        if config["validation_candidate"]:
            model_stats[model]["validation"] += 1
        model_stats[model]["throughputs"].append(config["predicted_throughput_gbits_per_sec"])

    for model in sorted(model_stats.keys()):
        stats = model_stats[model]
        max_tp = max(stats["throughputs"])
        min_tp = min(stats["throughputs"])
        print(f"  {model:20s}: {stats['total']:4d} configs ({stats['validation']:2d} validation) | TP: {max_tp:.2f} - {min_tp:.2f}")

    print(f"\n{'='*80}")
    print("Export complete!")
    print(f"{'='*80}")
    print(f"\nOutput directory: {output_dir}/")
    print(f"\nKey file:")
    print(f"  • {side}_pareto_validation_configs.json  - Combined JSON with all Pareto configs")
    print(f"\nUse sweep_configs/gen_sweep_configs.py to generate Scala configs from this JSON.")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Export Pareto configs from JSON files to CSV format."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help="Directory containing pareto_{side}_{model}.json files",
    )
    parser.add_argument(
        "--side",
        choices=["des", "ser"],
        required=True,
        help="Which side: des (deserializer) or ser (serializer)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory (default: same as input-dir)",
    )
    return parser.parse_args()


def main() -> None:
    """Main execution function."""
    args = parse_args()

    # Default output to input directory
    output_dir = args.output_dir if args.output_dir else args.input_dir

    print(f"\n{'='*80}")
    print("Pareto Config CSV Export")
    print(f"{'='*80}")
    print(f"Input directory:  {args.input_dir}")
    print(f"Output directory: {output_dir}")
    print(f"Side:             {args.side}")

    # Find all Pareto JSON files
    pareto_files = find_pareto_files(args.input_dir, args.side)

    if not pareto_files:
        print(f"\nERROR: No Pareto JSON files found in {args.input_dir}")
        print(f"       Expected pattern: pareto_{args.side}_*.json")
        return

    print(f"\nFound {len(pareto_files)} Pareto files:")
    for model_type, path in sorted(pareto_files.items()):
        print(f"  • {model_type:20s} -> {path.name}")

    # Export to JSON
    export_configs_to_json(pareto_files, args.side, output_dir)


if __name__ == "__main__":
    main()
