#!/usr/bin/env python3
"""
Generate Scala Config classes from Pareto validation JSON files.

Reads the combined Pareto validation JSON (generated by ml_model/export_pareto_configs.py)
and creates Scala Config classes for validation candidates only.

Usage:
    python3 gen_pareto_validation_configs.py \
        --input ../ml_model/results/.../des_pareto_validation_configs.json \
        --output ./ProtoAccelParetoValidationConfigs.scala

Output:
    Scala file with ProtoAccel{Des,Ser}ParetoValidation{ACRONYM+VALUE}*Config classes
    for each validation candidate in the Pareto front.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Import naming tables from gen_sweep_configs
from gen_sweep_configs import (
    DES_ACRONYM_LABEL_BY_KEY,
    DES_KEYS,
    DES_WITH_CLASS_BY_KEY,
    SER_ACRONYM_LABEL_BY_KEY,
    SER_KEYS,
    SER_WITH_CLASS_BY_KEY,
    BASE_FRAGMENTS,
)


def load_pareto_json(path: Path) -> dict[str, Any]:
    """Load Pareto validation JSON file."""
    with open(path, "r") as f:
        return json.load(f)


def encode_combo_name(combo: dict[str, int], name_keys: tuple[str, ...], acronym_map: dict[str, str]) -> str:
    """Return the acronym+value encoding for combo."""
    return "".join(f"{acronym_map[k]}{combo[k]}" for k in name_keys if k in combo)


def generate_scala_config_class(
    config: dict[str, Any],
    side: str,
    class_prefix: str,
) -> str:
    """Generate a Scala Config class for one Pareto config."""
    if side == "des":
        acronyms = DES_ACRONYM_LABEL_BY_KEY
        keys = DES_KEYS
        with_classes = DES_WITH_CLASS_BY_KEY
    else:
        acronyms = SER_ACRONYM_LABEL_BY_KEY
        keys = SER_KEYS
        with_classes = SER_WITH_CLASS_BY_KEY

    # Extract parameter values
    params = {k: config[k] for k in keys if k in config}

    # Generate class name
    acronym_suffix = encode_combo_name(params, keys, acronyms)
    class_name = f"{class_prefix}{acronym_suffix}Config"

    # Generate fragments (WithClass statements)
    fragments = []
    for key in keys:
        if key in params:
            with_class = with_classes[key]
            value = params[key]
            fragments.append(f"  new {with_class}({value}) ++")

    # Combine into class definition
    lines = [
        f"class {class_name} extends Config(",
    ]
    lines.extend(fragments)
    lines.append(BASE_FRAGMENTS)

    return "\n".join(lines)


def generate_scala_file(
    pareto_data: dict[str, Any],
    output_path: Path,
) -> None:
    """Generate Scala file with all validation candidate configs."""
    side = pareto_data["side"]
    side_name = "Des" if side == "des" else "Ser"
    class_prefix = f"ProtoAccel{side_name}ParetoValidation"

    # Filter to validation candidates only
    all_configs = pareto_data["configs"]
    validation_configs = [c for c in all_configs if c["validation_candidate"]]

    print(f"\nGenerating Scala configs for {side}:")
    print(f"  Total configs: {len(all_configs)}")
    print(f"  Validation candidates: {len(validation_configs)}")

    # Generate header
    lines = [
        "package chipyard",
        "",
        "import org.chipsalliance.cde.config.Config",
        "import protoacc._",
        "",
        "// Generated from Pareto validation JSON",
        f"// Side: {side}",
        f"// Total validation candidates: {len(validation_configs)}",
        f"// Models: {', '.join(pareto_data['models'])}",
        "",
        f"object ProtoAccel{side_name}ParetoValidationConfigs {{",
        "",
        f"  /** CONFIG= names for validation candidate classes (basename only). */",
        f"  val allConfigNames: Seq[String] = Seq(",
    ]

    # Generate config name list
    config_names = []
    for config in validation_configs:
        config_name = config["config_name"].replace("Config", "")
        config_names.append(f'    "{config_name}"')

    # Add commas to all but the last
    for i in range(len(config_names) - 1):
        config_names[i] += ","

    lines.extend(config_names)
    lines.append("  )")
    lines.append("")
    lines.append("}")
    lines.append("")

    # Generate config classes
    for i, config in enumerate(validation_configs, 1):
        lines.append(f"// Validation candidate {i}/{len(validation_configs)}")
        lines.append(f"// Model: {config['model_type']}")
        lines.append(f"// Predicted throughput: {config['predicted_throughput_gbits_per_sec']:.2f} Gbit/s")

        if "predicted_cost" in config:
            lines.append(f"// Predicted cost: {config['predicted_cost']:.2f}")
        elif "predicted_logic_cells" in config:
            lines.append(f"// Predicted logic cells: {config['predicted_logic_cells']:.0f}")
            lines.append(f"// Predicted RAM bits: {config['predicted_ram_bits']:.0f}")

        class_def = generate_scala_config_class(config, side, class_prefix)
        lines.append(class_def)
        lines.append("")

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"\n✓ Generated {len(validation_configs)} config classes")
    print(f"✓ Saved to: {output_path}")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate Scala Config classes from Pareto validation JSON."
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Path to {side}_pareto_validation_configs.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output Scala file path (default: ProtoAccel{Side}ParetoValidationConfigs.scala in current dir)",
    )
    return parser.parse_args()


def main() -> None:
    """Main execution function."""
    args = parse_args()

    print(f"\n{'='*80}")
    print("Pareto Validation Scala Config Generation")
    print(f"{'='*80}")
    print(f"Input: {args.input}")

    # Load Pareto JSON
    if not args.input.exists():
        print(f"\nERROR: Input file not found: {args.input}")
        sys.exit(1)

    pareto_data = load_pareto_json(args.input)
    side = pareto_data["side"]
    side_name = "Des" if side == "des" else "Ser"

    # Determine output path
    if args.output:
        output_path = args.output
    else:
        output_path = Path(f"ProtoAccel{side_name}ParetoValidationConfigs.scala")

    print(f"Output: {output_path}")

    # Generate Scala file
    generate_scala_file(pareto_data, output_path)

    print(f"\n{'='*80}")
    print("Generation complete!")
    print(f"{'='*80}")
    print(f"\nNext steps:")
    print(f"  1. Copy {output_path} to chipyard/src/main/scala/config/")
    print(f"  2. Run synthesis on validation candidates")
    print(f"  3. Compare predictions with actual measurements")


if __name__ == "__main__":
    main()
