#!/usr/bin/env python3
"""
Generate Scala Config classes and sweep CSVs from Pareto validation JSON files.

Reads the combined Pareto validation JSON (generated by
``ml_model/export_pareto_configs.py``) and produces two artifacts for
validation candidates:

  1. A Scala file with ``ProtoAccel{Des,Ser}ParetoValidation{ACRONYM+VALUE}*Config``
     classes so chipyard can elaborate/build them.
  2. A sweep CSV (``{side}_pareto_validation_sweep_configs.csv``) in the same
     schema as ``sweep_configs/yosys_synth_sweep_configs.csv`` -- header:
     ``config_name,side,sample_group,<des_*>,<ser_*>``. This is what
     ``run_combined_sweep.sh`` and ``run_yosys_sweep.sh`` consume to drive
     synth + verilator sim runs.

Inactive-side parameters are filled with defaults from
``hw_cost_model.defaults`` so the CSV schema is identical for des-side and
ser-side runs, and downstream parsers don't have to special-case missing
columns.

Usage:
    python3 gen_pareto_validation_configs.py \
        --input ./des_pareto_validation_configs.json \
        [--output-scala ./ProtoAccelDesParetoValidationConfigs.scala] \
        [--output-csv   ./des_pareto_validation_sweep_configs.csv]
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

# Import naming tables from gen_sweep_configs. This module also puts the
# lynx/ package dir on sys.path so hw_cost_model imports work when this
# script is run as ``python3 gen_pareto_validation_configs.py``.
from gen_sweep_configs import (
    BASE_FRAGMENTS,
    CSV_COLUMNS,
    CSV_PARAM_KEYS,
    DEFAULT_PARAM_VALUES,
    DES_ACRONYM_LABEL_BY_KEY,
    DES_KEYS,
    DES_WITH_CLASS_BY_KEY,
    SER_ACRONYM_LABEL_BY_KEY,
    SER_KEYS,
    SER_WITH_CLASS_BY_KEY,
)


PARETO_VALIDATION_SAMPLE_GROUP = "pareto_validation"


def load_pareto_json(path: Path) -> dict[str, Any]:
    """Load Pareto validation JSON file."""
    with open(path, "r") as f:
        return json.load(f)


def encode_combo_name(combo: dict[str, int], name_keys: tuple[str, ...], acronym_map: dict[str, str]) -> str:
    """Return the acronym+value encoding for combo."""
    return "".join(f"{acronym_map[k]}{combo[k]}" for k in name_keys if k in combo)


def _side_tables(side: str) -> Tuple[Tuple[str, ...], Dict[str, str], Dict[str, str], str]:
    """Return (name_keys, acronym_map, with_class_map, class_prefix) for side."""
    if side == "des":
        return DES_KEYS, DES_ACRONYM_LABEL_BY_KEY, DES_WITH_CLASS_BY_KEY, "ProtoAccelDesParetoValidation"
    if side == "ser":
        return SER_KEYS, SER_ACRONYM_LABEL_BY_KEY, SER_WITH_CLASS_BY_KEY, "ProtoAccelSerParetoValidation"
    raise SystemExit(f"Unknown side: {side!r} (expected 'des' or 'ser')")


def config_class_name(config: dict[str, Any], side: str) -> str:
    """Return the Scala class name generated for this config.

    Kept as a single source of truth so the Scala class name and the CSV
    ``config_name`` column always agree (the sweep runners key on this).
    """
    name_keys, acronyms, _wc, class_prefix = _side_tables(side)
    params = {k: config[k] for k in name_keys if k in config}
    return f"{class_prefix}{encode_combo_name(params, name_keys, acronyms)}Config"


def generate_scala_config_class(
    config: dict[str, Any],
    side: str,
) -> str:
    """Generate a Scala Config class for one Pareto config."""
    name_keys, _acronyms, with_classes, _class_prefix = _side_tables(side)

    class_name = config_class_name(config, side)
    params = {k: config[k] for k in name_keys if k in config}

    fragments = [
        f"  new {with_classes[key]}({params[key]}) ++"
        for key in name_keys
        if key in params
    ]

    lines = [f"class {class_name} extends Config("]
    lines.extend(fragments)
    lines.append(BASE_FRAGMENTS)
    return "\n".join(lines)


def generate_scala_file(
    pareto_data: dict[str, Any],
    output_path: Path,
    validation_configs: List[dict[str, Any]],
) -> None:
    """Generate Scala file with all validation candidate configs."""
    side = pareto_data["side"]
    side_name = "Des" if side == "des" else "Ser"

    print(f"\nGenerating Scala configs for {side}:")
    print(f"  Total configs: {len(pareto_data['configs'])}")
    print(f"  Validation candidates: {len(validation_configs)}")

    lines = [
        "package chipyard",
        "",
        "import org.chipsalliance.cde.config.Config",
        "import protoacc._",
        "",
        "// Generated from Pareto validation JSON",
        f"// Side: {side}",
        f"// Total validation candidates: {len(validation_configs)}",
        f"// Models: {', '.join(pareto_data['models'])}",
        "",
        f"object ProtoAccel{side_name}ParetoValidationConfigs {{",
        "",
        f"  /** CONFIG= names for validation candidate classes (basename only). */",
        f"  val allConfigNames: Seq[String] = Seq(",
    ]

    config_names = [
        f'    "{config_class_name(c, side)}"' for c in validation_configs
    ]
    for i in range(len(config_names) - 1):
        config_names[i] += ","

    lines.extend(config_names)
    lines.append("  )")
    lines.append("")
    lines.append("}")
    lines.append("")

    for i, config in enumerate(validation_configs, 1):
        lines.append(f"// Validation candidate {i}/{len(validation_configs)}")
        lines.append(f"// Model: {config['model_type']}")
        lines.append(f"// Predicted throughput: {config['predicted_throughput_gbits_per_sec']:.2f} Gbit/s")

        if "predicted_cost" in config:
            lines.append(f"// Predicted cost: {config['predicted_cost']:.2f}")
        elif "predicted_logic_cells" in config:
            lines.append(f"// Predicted logic cells: {config['predicted_logic_cells']:.0f}")
            lines.append(f"// Predicted RAM bits: {config['predicted_ram_bits']:.0f}")

        class_def = generate_scala_config_class(config, side)
        lines.append(class_def)
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"\nGenerated {len(validation_configs)} config classes")
    print(f"Saved to: {output_path}")


def generate_sweep_csv(
    pareto_data: dict[str, Any],
    output_path: Path,
    validation_configs: List[dict[str, Any]],
) -> None:
    """Emit a sweep CSV in the same schema as ``yosys_synth_sweep_configs.csv``.

    Columns: ``config_name,side,sample_group,<des_*>,<ser_*>``. Inactive-side
    columns are filled from ``DEFAULT_PARAM_VALUES`` so downstream readers
    always see the full parameter set, matching what
    ``gen_sweep_configs.py`` writes for the synth-training and random sweeps.

    Deduplicated by ``config_name`` (the class-name encoding). The
    validation JSON often has multiple entries per unique parameter combo
    -- e.g. the same combo picked by SVR and neural -- and the sweep
    runners key on ``config_name``, so a single row per class is the
    right unit.
    """
    side = pareto_data["side"]

    rows: List[Dict[str, Any]] = []
    seen: set[str] = set()
    for config in validation_configs:
        cls = config_class_name(config, side)
        if cls in seen:
            continue
        seen.add(cls)
        row: Dict[str, Any] = {
            "config_name": cls,
            "side": side,
            "sample_group": PARETO_VALIDATION_SAMPLE_GROUP,
        }
        # Fill every param column: this side's from the JSON, the other
        # side's from defaults so the CSV width is stable.
        for key in CSV_PARAM_KEYS:
            row[key] = config.get(key, DEFAULT_PARAM_VALUES[key])
        rows.append(row)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(CSV_COLUMNS), extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)

    print(f"\nWrote sweep CSV ({len(rows)} unique configs)")
    print(f"Saved to: {output_path}")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate Scala Config classes and sweep CSVs from Pareto validation JSON."
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Path to {side}_pareto_validation_configs.json",
    )
    parser.add_argument(
        "--output-scala",
        type=Path,
        default=None,
        help="Output Scala file path (default: ProtoAccel{Side}ParetoValidationConfigs.scala in current dir)",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help=(
            "Output sweep CSV path (default: {side}_pareto_validation_sweep_configs.csv "
            "next to the input JSON). Schema matches yosys_synth_sweep_configs.csv."
        ),
    )
    # Kept for backwards-compat with the old CLI (--output previously meant
    # the Scala file). If passed, treat as an alias for --output-scala.
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=argparse.SUPPRESS,
    )
    return parser.parse_args()


def main() -> None:
    """Main execution function."""
    args = parse_args()

    print(f"\n{'='*80}")
    print("Pareto Validation Scala + CSV Generation")
    print(f"{'='*80}")
    print(f"Input: {args.input}")

    if not args.input.exists():
        print(f"\nERROR: Input file not found: {args.input}")
        sys.exit(1)

    pareto_data = load_pareto_json(args.input)
    side = pareto_data["side"]
    side_name = "Des" if side == "des" else "Ser"

    validation_configs = [c for c in pareto_data["configs"] if c["validation_candidate"]]

    # Deduplicate validation configs by their Scala class name (the encoding of the parameter combo).
    unique_validation_configs: Dict[str, dict[str, Any]] = {}
    for config in validation_configs:
        cls_name = config_class_name(config, side)
        if cls_name not in unique_validation_configs:
            unique_validation_configs[cls_name] = config
    validation_configs = list(unique_validation_configs.values())

    scala_path = args.output_scala or args.output or Path(
        f"ProtoAccel{side_name}ParetoValidationConfigs.scala"
    )
    csv_path = args.output_csv or (
        args.input.parent / f"{side}_pareto_validation_sweep_configs.csv"
    )

    print(f"Scala output: {scala_path}")
    print(f"CSV output:   {csv_path}")

    generate_scala_file(pareto_data, scala_path, validation_configs)
    generate_sweep_csv(pareto_data, csv_path, validation_configs)

    print(f"\n{'='*80}")
    print("Generation complete!")
    print(f"{'='*80}")
    print(f"\nNext steps:")
    print(f"  1. Copy {scala_path} to chipyard/src/main/scala/config/")
    print(f"  2. Run the combined synth+sim sweep:")
    print(f"       hw_cost_model/run_combined_sweep.sh \\")
    print(f"         --side {side} --sweep-csv {csv_path} \\")
    print(f"         --synth-output <path> --sim-output <path>")
    print(f"  3. Compare predictions with actual measurements")


if __name__ == "__main__":
    main()
