from itertools import product
from pathlib import Path

OUT = Path("../generators/chipyard/src/main/scala/config/Sha3SweepConfigs.scala")

WIDTHS = [64]
STAGES = [1, 2, 3, 4]
FASTM  = [False, True]
BUFFS  = [False, True]
KECCAK = [False, True]

def b01(x: bool) -> str:
    return "1" if x else "0"

def cname(w, s, fm, bs, k):
    # Use camelCase instead of underscores to avoid chipyard's underscore splitting
    return f"Sha3RocketW{w}S{s}Fm{b01(fm)}Bs{b01(bs)}K{b01(k)}"

lines = []
lines.append("package chipyard\n")
lines.append("import org.chipsalliance.cde.config.Config\n\n")
lines.append("// AUTO-GENERATED by scripts/gen_sha3_sweep_configs.py\n\n")

for w, s, fm, bs, k in product(WIDTHS, STAGES, FASTM, BUFFS, KECCAK):
    cls = cname(w, s, fm, bs, k)
    lines.append(f"class {cls} extends Config(\n")
    lines.append( "  new chipyard.config.WithNPerfCounters ++\n")
    lines.append(f"  new sha3.WithSha3Accel(width={w}, stages={s}, fastMem={str(fm).lower()}, bufferSram={str(bs).lower()}, keccak={str(k).lower()}) ++\n")
    lines.append( "  new freechips.rocketchip.subsystem.WithNBigCores(1) ++\n")
    lines.append( "  new chipyard.config.AbstractConfig)\n\n")

OUT.write_text("".join(lines))
print(f"Wrote {OUT} with {len(WIDTHS)*len(STAGES)*len(FASTM)*len(BUFFS)*len(KECCAK)} configs")